spring.application.name=productos-api

# CONFIGURACION DE POSTGRESQL
spring.datasource.url=jdbc:postgresql://localhost:5432/productos_db
spring.datasource.username=postgres
spring.datasource.password=TU_PASSWORD

# CONFIGURACION DE JPA E HIBERNATE
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.open-in-view=false

# LABORATORIO 09 - CONFIGURACION JWT
app.jwt.issuer=tienda-api
app.jwt.ttl-minutes=30
app.jwt.secret-base64=${JWT_SECRET_BASE64}
