spring.application.name=semana4-api-rest
server.port=8082

# Muestra detalles básicos de error durante el laboratorio. 
# En producción no se recomienda exponer mensajes internos. 
server.error.include-message=always 
server.error.include-binding-errors=always
